# Generated by Django 5.2.1 on 2026-05-25 15:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price_extra', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Доп. цена')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('working_hours', models.CharField(default='09:00-22:00', max_length=100, verbose_name='Часы работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Точка самовывоза',
                'verbose_name_plural': 'Точки самовывоза',
            },
        ),
        migrations.CreateModel(
            name='PizzaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория пиццы',
                'verbose_name_plural': 'Категории пиццы',
            },
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('small', 'Маленькая (25 см)'), ('medium', 'Средняя (30 см)'), ('large', 'Большая (35 см)'), ('xlarge', 'Семейная (40 см)')], max_length=10, unique=True, verbose_name='Размер')),
                ('diameter_cm', models.PositiveSmallIntegerField(verbose_name='Диаметр (см)')),
            ],
            options={
                'verbose_name': 'Размер пиццы',
                'verbose_name_plural': 'Размеры пиццы',
            },
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Соус',
                'verbose_name_plural': 'Соусы',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(blank=True, max_length=100, verbose_name='Транспорт')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('hired_at', models.DateField(auto_now_add=True, verbose_name='Дата найма')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to='users.userprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьеры',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('preparing', 'Готовится'), ('delivering', 'Доставляется'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='new', max_length=15, verbose_name='Статус')),
                ('delivery_type', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], default='delivery', max_length=10, verbose_name='Тип доставки')),
                ('delivery_address', models.CharField(blank=True, max_length=300, verbose_name='Адрес доставки')),
                ('promo_code', models.CharField(blank=True, max_length=50, verbose_name='Промокод')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Скидка %')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итого')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.userprofile', verbose_name='Клиент')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.courier', verbose_name='Курьер')),
                ('pickup_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.pickuppoint', verbose_name='Точка самовывоза')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pizzas/', verbose_name='Фото')),
                ('ingredients', models.TextField(blank=True, verbose_name='Состав')),
                ('weight_g', models.PositiveIntegerField(default=500, verbose_name='Вес (г)')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Калории')),
                ('is_active', models.BooleanField(default=True, verbose_name='В продаже')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizzas', to='shop.pizzacategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пицца',
                'verbose_name_plural': 'Пиццы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PizzaPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_prices', to='shop.pizza')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.pizzasize')),
            ],
            options={
                'verbose_name': 'Цена пиццы',
                'verbose_name_plural': 'Цены пиццы',
                'unique_together': {('pizza', 'size')},
            },
        ),
        migrations.AddField(
            model_name='pizza',
            name='sizes',
            field=models.ManyToManyField(through='shop.PizzaPrice', to='shop.pizzasize', verbose_name='Размеры'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за шт.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Заказ')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.pizza', verbose_name='Пицца')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.pizzasize', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.AddField(
            model_name='pizza',
            name='sauce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizzas', to='shop.sauce', verbose_name='Соус'),
        ),
    ]
